### ISSUE TITLE
Dealing with consistent missing weather patterns

### ISSUE THREAD

**Issue by matthewgee** [impactlab/caltrack-betatest#16]
Check for consistent missing patterns in weather station files. Is this a problem?

**Comment by houghb** [comment]
I have found that there are consistent missing weather patterns in some of the ISD weather data for certain stations (for example, PALO-ALTO_724937 has large chunks of hours consistently missing every day).  Other stations have similar issues.  Not sure if this is a problem...

**Comment by mcgeeyoung** [comment]
@houghb Would it be worth coming up with a test? Either for consistent missing data or for whether or not it's a problem?

**Comment by houghb** [comment]
With our current monthly methods the only impact this would have is to change the average daily temperature a little, and given our fixed balance points I doubt this is much of a problem for monthly (intuition, not based on any exploration).  When we get to daily modeling this might become a larger issue, maybe we should wait to see if it is a problem then?

**Comment by matthewgee** [comment]
@houghb @mcgeeyoung see last comment on [issue 10](https://github.com/impactlab/caltrack-betatest/issues/10). Let determine if this is an issue we need to deal with as part of the discussion around the use of hourly weather data for daily methods.
