### ISSUE TITLE
Clarify the use of the 'work start date' and 'work end date' fields in the data prep README

### ISSUE THREAD

**Issue by matthewgee** [impactlab/caltrack-betatest#24]
From Blake: the README for data prep doesn’t tell us to use the `work start date` or `work end date` columns of the raw csv files (even if they are populated), it just instructs us to set the dates using the other fields.  Can we clarify using one approach vs the other and make sure the README is updated if necessary?

**Comment by matthewgee** [comment]
The `work start date` and `work end date` fields will be defined using the column mapping provided by Build It Green using proxy fields for all projects done before July 1st, 2016. These fields are currently defined in the data preparation README.

After July 1, 2016, CalTrack implementations should use official `work start date` and `work end date` fields provided by aggregators instead of the proxy fields.

**Comment by houghb** [comment]
Follow-up on this - Matt's response lays out a change that will need to be made to the specs in the future.  How do we incorporate this feedback into the existing methods specs (or make a note to update the methods specs at some point in the future)?

**Comment by mcgeeyoung** [comment]
Good question. I recommend an "Ongoing Issues" section where maintenance issues like this can be surfaced.

**Comment by matthewgee** [comment]
I think this issue is now resolved since we provided guidance on proxy field use for pre-July 2016 projects and have included the field requirements for post-July 2016 projects. There shouldn't be any future changes to this particular guidance now.
