### ISSUE TITLE
Which projects are we generating stats for in Analysis I?

### ISSUE THREAD

**Issue by houghb** [impactlab/caltrack-betatest#27]
Can we clarify which projects we should be generating summary stats for in the Analysis stage?  All projects in a given calendar year?  We've been looking at projects that start/end in 2014 so far.

**Comment by matthewgee** [comment]
We should run savings calculations on all projects that meet data sufficiency criteria, i.e. have a full year pre and a full year post intervention.

**Comment by matthewgee** [comment]
Added to README
