### ISSUE TITLE
Considering how CalTrack monthly methods handle homes with solar, EVs, and batteries

### ISSUE THREAD

**Issue by matthewgee** [impactlab/caltrack-betatest#36]
The handling of homes with solar was discussed extensively in the working group in meetings [4](https://docs.google.com/document/d/11pfeh856kwt5VixkvdVB4e2vvgzdY908PiosjuIUqGA/edit?usp=sharing) and [5,](https://docs.google.com/document/d/18pr0qt2pR9K50go85rZu-i8hx5ZNFgHtE4pu5479Sro/edit?usp=sharing) and after inspection of the data, it was decided that solar homes could reliably (although with exceptions) be detected from the usage files provided by PG&E and in Share My Data extracts using the presence of negative values as indicators. It was decided that homes flagged as having solar through this method would be dropped from the P4P savings analysis and, unless solar production data could be provided, would not be included in P4P payments. This is currently captured in the [data-prep section of the specification](https://github.com/impactlab/caltrack-betatest/tree/master/data-prep).

**Comment by houghb** [comment]
This was also discussed in a closed issue (https://github.com/impactlab/caltrack-betatest/issues/4).  I don't think any of the reasons we decided not to include net metered homes have changed - what is the question being raised in this issue?  @matthewgee are you suggesting we revisit this discussion and consider trying to do something with premises that are net metered?

**Comment by mcgeeyoung** [comment]
@houghb I think we just wanted to provide some clarity around the lines we are drawing. For example, are we going to come up with methods for "adding" solar data to homes with net metering? My inclination is to be fairly strict in what we include here and to leave the edge cases and exceptions for a future endeavor.

**Comment by matthewgee** [comment]
@houghb Elaborating on the above, the issue that a few folks from the technical working group brought up in December was whether the spec should include additional considerations for homes with Solar, EV, and batteries. 

In particular, two main issues:

1. Can we reliably exclude homes with EV and batteries? Currently the spec only outlines a procedure for omitting homes with solar by looking for negative values in the usage data to flag for solar generation. We don't have any procedures for flagging homes with EV or batteries, and haven't explicitly stated that they should be excluded. I think, for the purposes of v1, they should be and we should add their explicit exclusion to the spec. 

2. Should we included in the method the use of additional data from solar, EVs, or batteries? This is @mcgeeyoung's point. Eventually, it would be helpful to have the ability to include homes with solar, EV, and batteries in AHUC and P4P programs and to do this, the CalTRACK methods will need to be able to net out solar production and charging data. I don't think it's within scope to include it in v1 or v1.1, but since it was brought up in December as an issue worth discussing as a working group, let's seed the discussion.

**Comment by jbackusm** [comment]
@matthewgee On your first issue: do we expect the current monthly methods to break down when applied to homes with batteries or EV? I would think the same models relating usage to degree-days could be applied to these cases, at least at the monthly level. I don't think the presence of batteries would affect the monthly usage very much, and at this level EV's might just show up as increased baseload, right? In that case, it doesn't seem important to exclude batteries or EV from the monthly analysis, unless the EV is new at some point in the pre/post-treatment periods...which perhaps relates to another comment of mine on a different issue, regarding large exogenous changes in usage.

**Comment by houghb** [comment]
@matthewgee, a couple of follow up points:

With regard to your issue 1; The current data cleaning and integration spec (and your description of it above) is not in total agreement with the actual data cleaning steps that Marc followed for the cleaned electric data that OEE distributed to the rest of the group (we had a single beta tester clean the data and distribute it to the other working group members since beta testers couldn't arrive at the same clean data set by following the current specs).  Rather than looking for negative values in the usage data (there are no negative values), the current procedure looked for usage rows with `DIR=R`, and then, in addition to those, the electric xref table is also checked and any `char_prem_id` values with `net_mtr_ind=Y`.  The union of these two lists is all of the premises that we consider net metered.  Regarding EV and batteries, I share John's assessment and questions above.  Have any of the CalTRACK stakeholders asked that homes with EV or batteries be removed?  

With respect to your issue 2; I agree that it might eventually be useful to include homes with solar, etc, but we don't have enough information (in the data files currently available) to do this (see Issue #4).  I haven't heard any indication that the additional data necessary to do this is going to be available anytime in the foreseeable future, so I suggest we not spend time trying to discuss what we might do eventually with such an unknown data source.

**Comment by gkagnew** [comment]
Re identifying solar, negative values or DIR=R are ways to identify arrays that are large enough to spin the meter backward during some hour of the year.  Spoke to one of our engineers and he said this will catch 80 or even 90% of houses with solar but not necessarily all.  I think the union with a net meter indicator makes sense as discussed by @houghb.  If P4P spreads to other IOUs, having that net meter indicator in addition to the hourly interval information (negative or R) will be important.

**Comment by matthewgee** [comment]
@houghb @jbackusm Great discussion. Following up on each point:

1. Updating cleaning specification to reflect tested approach to solar flagging. Agreed on this, the current spec doesn't capture completely the procedure we use in the beta test, which I think is what we want included in the spec. We'll add this to the cleaning spec pull request and not it in the "what needs to be added to the cleaning spec" issue.

2. Did working group members raise the issue of EV and batteries? Yes. In the comments on the 2017 action plan, both DNV and Savvy raised the issue. Here's the quote from the comments on the planning doc:

"▪	Savvy: Specs needed for Homes with solar and EV - Add EV to solar production data. It seems like we also need a plan for EV homes based on EV ramp up expectations over the next two years.
▪	DNVGL: Explicit production data or program indication of EV date need to be available to estimate the normalized metered savings for these homes. This issue is common for all use cases. Normalization should include whether part of the pre or post period added major load changes such as PV and EV. "

I think their's a reasonable argument to be made that, because EV, PV, and batteries can change a home's total usage patterns significantly, independent of any EE investment, including homes that are know to have any of these three characteristics added during the baseline period in the sample in calculating either payable savings in P4P or adjusting software-based incentives could distort the gross savings estimate specified in the monthly methods. 

I agree that if both EV and batteries are present for the duration of the specified pre/post period, then it will show up in baseload and shouldn't cause too much of a problem in monthly savings estimation.

I agree that we should not try and solve for including production or charging data in v1 or v1.1 of the spec since the availability of this data is really uncertain (Orange Button is still very much under development). 

So, how about the following:

For CalTRACK v1 Monthly methods, homes with PV will be excluded using the updated flagging approach detailed above. For EV and batteries, if it is know that a household added either during the pre/post period, they are excluded from the sample. This of course has important programmatic impacts, so we should make sure @leif chimes in.

**Comment by houghb** [comment]
"For CalTRACK v1 Monthly methods, homes with PV will be excluded using the updated flagging approach detailed above."
- this sounds good to us

"For EV and batteries, if it is know that a household added either during the pre/post period, they are excluded from the sample."
- also fine with us (with data available in CalTRACK beta we never have this information, so unless we decide to infer this from usage patterns it doesn't affect anything we will be doing).
