### ISSUE TITLE
What are the defined use cases for daily methods?

### ISSUE THREAD

**Issue by houghb** [impactlab/caltrack-betatest#51]
In our work last fall there was some confusion because all of the beta testers were not on the same page regarding the actual use cases for the work we were doing until later in the project.  I'd like to get the purpose/use cases for daily methods established before we start working on the daily methods so we can make appropriate decisions on methods.  

Do we have an explicit list of use cases from Leif or others for this work so we can limit scope appropriately?

**Comment by LeifMagnuson** [comment]
Hi Blake, The use case is the Pay for Performance Payable energy savings calculation - simple pre-/post with weather normalization.  If you guys can get those methods worked out, we can build from there. For example, to do our claimable savings calculation I just run a comparison group through the methods and compare the treatment and comparison group savings to arrive at net savings. Is that helpful?

**Comment by houghb** [comment]
Thanks, @LeifMagnuson, limiting to that use case is helpful.  I'm not convinced that your proposed means of doing a claimable savings calculation is quite that simple, nor does it actually give you net savings, but we can talk about that offline.

**Comment by mcgeeyoung** [comment]
With clarity around the primary use case established, I'm going to close this issue.
