### ISSUE TITLE
To-Do list for daily methods development

### ISSUE THREAD

**Issue by mcgeeyoung** [impactlab/caltrack-betatest#53]
ToDo’s:

Data Sources

- Obtain hourly weather data
- Re-use 100 home dataset from monthly test? 

Data Preparation

- Share daily electricity and gas data file (if necessary)
- Share hourly weather data file
- [alternately] Share data file with weather, project, and consumption data already linked
- Provide guidance on record linking
- Determine data sufficiency criteria for weather
- Determine data sufficiency criteria for usage data
- Determine pre-post period guidelines

Data Analysis

- Determine first stage equation
- Confirm method for calculating HDD and CDD
- Determine model selection criteria (range and optimization algorithm)
- Fitness criteria for model selection
- Regularization?

Outputs and Aggregation

- Additional post-estimation values (or stick with what we did with monthly)
- What weights and/or exclusion criteria should apply, if any, to aggregations of site-level savings?
- What form of final dataset do we want to provide for future testers to compare against?

**Comment by houghb** [comment]
> Obtain hourly weather data

I think there may be some wires crossed somewhere, my understanding from @matthewgee was that we were going to use daily average weather data for daily like in our revised monthly specs?  If using hourly data we need to revisit the data cleaning specs for this data source.

> Re-use 100 home dataset from monthly test?

We're fine with this as a starting point (assuming at some point once issues with the small dataset are worked out we will look at results for the whole dataset).

Your description of the `Data Preparation` section makes it sound like the plan is to take a similar approach as we did in the fall where beta testers are not going to test the data preparation steps to make sure they work to arrive at similar cleaned data?  If we are going to publish data prep specs then I think we should take another stab at getting to the same cleaned data.  With a better thought-out approach based on our smaller test dataset this seems possible.

The rest of the outlined points sound reasonable as a plan to move forward.

**Comment by mcgeeyoung** [comment]
@houghb Was leaving the data prep options open...but makes sense to give the spec another shot if seems worthwhile.
