### ISSUE TITLE
starting point for stage one model for daily methods

### ISSUE THREAD

**Issue by houghb** [impactlab/caltrack-betatest#54]
I propose that for v1.1 we start with a standard PRISM model, and focus our discussion on how to do the best balance point optimization with this simple model before making it more complex (I expect the balance point discussion/exploration will take a while).  We started talking about balance point optimization last fall and deferred a more in depth exploration to whenever we started daily methods.  If we're able to tackle PRISM + balance point optimization with time to spare we could consider adding additional fixed effects to the model.  What do others think? @jfarland @gkagnew @matthewgee @mcgeeyoung

**Comment by matthewgee** [comment]
@houghb I agree. If we define the starting point of the first stage model as the most parameter constrained possible that we still feel is valid, then we also have a useful baseline model and model fit outs for making sequential fixed effect additions.

To be clear, this means leaving out day_of_week, weekend, and holiday fixed effects from the base model. Is that what you mean when you are thinking PRISM on daily data?

**Comment by houghb** [comment]
@matthewgee Yes, your clarification is exactly what I mean

**Comment by matthewgee** [comment]
I think we're in agreement here and have use the above as the starting point detailed above as the starting specification in [this daily methods google doc](https://docs.google.com/document/d/1hVeESqavpE6pZ7p0Scm7O4aBpaxkd2MQsPSkaULY5E8/edit#) so I'm going to close this issue.
