### ISSUE TITLE
daily usage data deduplication methods suggestion

### ISSUE THREAD

**Issue by houghb** [impactlab/caltrack-betatest#58]
The current daily analysis data prep spec includes this section for deduplicating usage data:

> **Deduplicate records based on combined attributes**
>- If two duplicate records have identical consumption traces and date ranges, drop one at random
>- If two duplicate records have identical consumption traces but different date ranges select the more complete record having more dates. * If the dates are contiguous, or there are overlapping dates with the same usage values, combine the two traces into a single trace.
>- If the records have the same date ranges, but different usage values, the project should be flagged and the record excluded from the sample.

To the second bullet point, instead of just selecting the record with more dates I suggest we select the record with the most complete data in the pre/post treatment years.  This would avoid the following hypothetical issue:
-  one duplicate record has 4 years of data, but that data ends one month after the treatment end date (in which case we would throw out this record for not having enough post treatment data)
- the other duplicate record has 3 years of data, but it completely covers the pre and post treatment years, so it could be included in the analysis.

My thought is that we never use more than one year's pretreatment data, so should prioritize having more postreatment data.

**Comment by mcgeeyoung** [comment]
Updated draft language @houghb close if you think it works
