### ISSUE TITLE
Add AHUP date rules to data-prep README

### ISSUE THREAD

**Issue by matthewgee** [impactlab/caltrack-betatest#7]

**Comment by houghb** [comment]
This issue has been resolved in the README and can be closed, although the language in the first bullet under "The following rules are used for determining `work end dates`:" could be revised to be a little bit clearer, for example:
- From the updated ‘AHUP’ file “CalTrack (AHUP) from 1_1_14__6_30_15_v2_FINAL_090816”
  - Column J - "Full Application Submitted" should be used for `work end date` unless there is a date in Column I ("Full Application Returned"), in which case Column H ("Full Application Started") is the better proxy for work finished.
