### ISSUE TITLE
Should we have separate project tables for electric and gas?

### ISSUE THREAD

**Issue by houghb** [impactlab/caltrack-betatest#9]
For the deduplication requirement we need to use either `Electric Service ID` or `Gas Service ID` as the key to group duplicates.  Whichever we choose, there are many rows where the opposite ID is empty (homes where there is either only electric service but no gas, or only gas but no electric) leading to many projects are merged into a single row. There are also many rows with multiple values of the opposite ID (for example, for a single `Electric Service ID` there can be multiple `Gas Service ID`s associated with it). Both of these lead to problems later if we need to associate a project with usage data.

Should we create two project tables ("electric_project_table" and "gas_project_table") to address this issue, and thus add an additional file to the Prepared Data Summary Statistics?

**Comment by houghb** [comment]
Since no response here I went ahead and added a new column to our projects table with the `sp_id` of the appropriate account in the cross reference tables (the `sp_id` from the electric cross reference table if there was an `Electric Service ID` in the project table, or if not then the `sp_id` from the gas cross reference table for the matching `Gas Service ID`) and used that `sp_id` column to merge duplicates.  There were 28 duplicate entries, only one of which has conflicting `Electric Service ID`s for a given `sp_id`.

**Comment by matthewgee** [comment]
@houghb good idea. let's go ahead and create separate gas_project_table and electric_project_tables to simplify. 

For the the one project to many usage files of one fuel type, the first determination is whether the traces are duplicate, overlapping, or distinct. Then we need to apply a rule for dealing with each case. I propose the following:

Classification of a usage trace as duplicate, overlapping, or distinct at the premise level:
- Duplicate if 99% of trace values for a timestamp are identical and covered time stamp range is identical
- Overlapping if 99% of trace values for identical time stamps are identical and time stamp ranges for the two traces differ.
- Distinct if <90% of non-zero traces values with the same time stamp are identical and the time stamp ranges are identical.

Rules for dealing with duplicate trace values.
- Duplicate: keep the first of the two traces by order when trace values are sorted in descending alphanumeric order by SAID.
- Overlapping: Keep the values for the first trace (by alphanumeric order of SAID) for overlapping timestamps and combine the trace values into a single trace for nonoverlapping timestamps. 
- Distinct: Assume that there are multiple meters per premise and combine two traces into one trace by summing values at each timestamp.

If that sounds good to you guys, I can add it to the README.

**Comment by houghb** [comment]
@matthewgee I probably won't have a chance to redo this to split the table into separate electric/gas lists (and adjust the rest of our cleaning/integration pipeline accordingly) before tomorrows meeting.  The solution I came up with (adding SPID to the projects table) worked well for us and has the added benefit of cleaning out projects for which we don't have cross reference information.  If you decide to make separate electric/gas tables we can see how the different approaches compare.
